### ISSUE TITLE
[DEFECT] HERON fails on PIP linux machine

### ISSUE THREAD

**Issue by alfoa** [idaholab/HERON#66] opened 2021-01-30 01:00 UTC
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
HERON tests to pass in a PIP machine (Machine where dependencies are installed via PIP)

##### What did you see instead?
8/10 tests fail

```
FAILED:
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/cashflows/Cashflows
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/labels/Labels
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/multimarket_fix_price/MultimarketFixPrice
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/min_demand/MinDemand
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/production_flex/ProductionFlex
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/validator/ValidatorExample
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/var_demand_fix_price/VarDemandFixPrice
Failed /home/civet/civet/build_0/raven/plugins/HERON/tests/integration_tests/var_demand_var_price/VarDemandVarPrice
```

##### Do you have a suggested fix for the development team?
N/A

**Describe how to Reproduce**
1. Install dependecies via PIP (linux machine)
2. run_tests --plugins --re=HERON
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Linux
 - Version: DEVEL
 - Dependencies Installation: PIP

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment] 2021-01-30 17:04
This is a duplicate of #33. Closing.

**Closed as completed by PaulTalbot-INL** 2021-01-30 17:04 UTC
Labels: defect, priority-critical

**Comment by alfoa** [comment] 2021-01-30 18:02
I change the label to the other one.
